apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: kb8li7ync-go 
  janus-idp.io/tekton: kb8li7ync-go
  backstage.io/kubernetes-id: kb8li7ync-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: kb8li7ync-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  