apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: kb8li7ync-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kb8li7ync-go 
  name: kb8li7ync-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: kb8li7ync-go 
